version: "3"

services:
  api:
    container_name: movie-logger-api
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/api
    tty: true
    command: >
      bash -c 'pip install -r requirements.txt --no-cache-dir && uvicorn src.main:app --reload --host 0.0.0.0 --port 8000'
