version: "3"

services:
  api:
    container_name: filmographub-api
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/api
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    command: >
      bash -c 'uvicorn src.main:app --reload --host 0.0.0.0 --port 8000'
    env_file: ./.env
